services:

  llama-cpp:
    container_name: llama-cpp
    runtime: nvidia
    restart: unless-stopped
    image: opencode-llama.cpp:latest
    networks:
      - llama_network
    volumes:
      - llama-cpp_data:/root/.cache/huggingface
      - ./models.ini:/models.ini
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command:
      - "--models-preset"
      - "/models.ini"
      - "--port"
      - "8080"
      - "--host"
      - "0.0.0.0"

  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    runtime: nvidia
    healthcheck:
      test: ollama --version || exit 1
    networks:
      - llama_network
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=0
      - OLLAMA_MAX_LOADED_MODELS=1

  openresty:
    container_name: openresty
    build:
      context: ./openresty
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "11434:11434"
      - "8080:8080"
    volumes:
      - ./openresty/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./openresty/coordinator.lua:/etc/nginx/lua/coordinator.lua
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - llama_network
      - enhasa_network
    depends_on:
      - ollama
      - llama-cpp

volumes:
  ollama_data:
  llama-cpp_data:

networks:
  llama_network:
  enhasa_network:
    external: true
