services:

  llama-cpp:
    profiles: ["managed"]
    runtime: nvidia
    restart: unless-stopped
    image: ghcr.io/ggml-org/llama.cpp:server
    networks:
      - core_network
    volumes:
      - llama-cpp_data:/root/.cache/huggingface
      - ./llama-cpp/models.ini:/models.ini
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command:
      - "--models-preset"
      - "/models.ini"
      - "--port"
      - "8080"
      - "--host"
      - "0.0.0.0"

  ollama:
    profiles: ["managed"]
    image: ollama/ollama
    restart: unless-stopped
    runtime: nvidia
    healthcheck:
      test: ollama --version || exit 1
    networks:
      - core_network
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=0
      - OLLAMA_MAX_LOADED_MODELS=1

  openresty:
    build:
      context: ./openresty
      dockerfile: Dockerfile
    user: root
    restart: unless-stopped
    ports:
      - "11434:11434"
      - "8080:8080"
    volumes:
      - ./openresty/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./openresty/coordinator.lua:/etc/nginx/lua/coordinator.lua
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core_network
      - enhasa_network

volumes:
  ollama_data:
  llama-cpp_data:

networks:
  core_network:
  enhasa_network:
    external: true
