#!/bin/bash
# gen_metrics.sh — Regenerate full-metrics.md from bench JSONs + models.ini
#
# Usage: ./tools/gen_metrics.sh
#
# For each models.ini entry, fills the metrics table from
# llama-cpp/models/<name>.json if present. Missing JSON → '—' / 'unverified'.
# Each model (including -coder variants) is benched independently — no copying.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INI="$ROOT/llama-cpp/models.ini"
MODELS_DIR="$ROOT/llama-cpp/models"
OUT="$ROOT/full-metrics.md"

python3 - "$INI" "$MODELS_DIR" "$OUT" << 'PYEOF'
import json, os, re, sys

ini_path, models_dir, out_path = sys.argv[1:4]

# ── Load models.ini metadata ────────────────────────────────
def get_section(content, name):
    m = re.search(r'\[' + re.escape(name) + r'\](.*?)(?=\n\[|\Z)', content, re.DOTALL)
    return m.group(1) if m else ''

def kv(sec, key, default=None):
    m = re.search(r'^\s*' + re.escape(key) + r'\s*=\s*(\S+)', sec, re.MULTILINE)
    return m.group(1) if m else default

with open(ini_path) as f:
    content = f.read()

names = []
for m in re.finditer(r'^\[([^\]]+)\]', content, re.MULTILINE):
    if m.group(1) != '*':
        names.append(m.group(1))

def fmt_ctx(ctx):
    if ctx is None: return '—'
    if isinstance(ctx, int) and ctx >= 1000:
        return f"{ctx // 1024}k" if ctx % 1024 == 0 else str(ctx)
    return str(ctx)

# ── Load JSON bench data ────────────────────────────────────
def load_json(name):
    p = os.path.join(models_dir, name + '.json')
    if not os.path.exists(p):
        return None
    try:
        with open(p) as f:
            return json.load(f)
    except Exception:
        return None

def bench_row(d):
    """Extract the 22 metric columns from a bench JSON dict."""
    if not d:
        return None
    sp = d.get('speed', {})
    rq = d.get('request', {})
    m  = d.get('mtp', {}) or {}
    hw = d.get('hardware', {}) or {}
    run = hw.get('run', {}) or {}
    cfg = d.get('config', {}) or {}
    return {
        'ctx': d.get('ctx'),
        'batch': d.get('batch'),
        'n_max': m.get('configured_n_max'),
        'p_min': m.get('configured_p_min'),
        'drafter': m.get('drafter'),
        'reasoning': cfg.get('reasoning'),
        'decode': sp.get('decode_t_s'),
        'prefill': sp.get('prefill_t_s'),
        'pre_ms': sp.get('prefill_ms'),
        'dec_ms': sp.get('decode_ms'),
        'pre_mtok': sp.get('prefill_ms_per_tok'),
        'dec_mtok': sp.get('decode_ms_per_tok'),
        'acc': m.get('acceptance'),
        'place': d.get('placement'),
        'cpu': run.get('avg_cpu_pct'),
        'gpu_util': run.get('avg_gpu_util_pct'),
        'temp': run.get('peak_temp_c'),
        'power': run.get('peak_power_w'),
        'vram': run.get('peak_vram_mib'),
        'ram': run.get('ram_used_mib'),
        'rss': run.get('rss_mib'),
    }

# ── Build rows (each model independent — no coder-copy) ─────
rows = []
for name in names:
    d = load_json(name)
    b = bench_row(d)
    if b is None:
        sec = get_section(content, name)
        meta = {
            'ctx': int(kv(sec, 'ctx-size')) if kv(sec, 'ctx-size') else None,
            'batch': kv(sec, 'batch-size'),
            'n_max': kv(sec, 'spec-draft-n-max'),
            'p_min': kv(sec, 'spec-draft-p-min'),
            'reasoning': kv(sec, 'reasoning', 'off'),
            'drafter': 'in-model' if 'draft-mtp' in sec else 'none',
        }
        b = {
            'ctx': meta['ctx'], 'batch': meta['batch'],
            'n_max': meta['n_max'], 'p_min': meta['p_min'],
            'drafter': meta['drafter'], 'reasoning': meta['reasoning'],
            'decode': None, 'prefill': None, 'pre_ms': None, 'dec_ms': None,
            'pre_mtok': None, 'dec_mtok': None, 'acc': None,
            'place': 'unverified', 'cpu': None, 'gpu_util': None,
            'temp': None, 'power': None, 'vram': None, 'ram': None, 'rss': None,
        }
    rows.append((name, b))

def f(v, fmt=None):
    if v is None or v == '' or (isinstance(v, float) and v == 0 and fmt):
        return '—'
    if fmt == 't2': return f"{v:.2f}"
    if fmt == 't1': return f"{v:.1f}"
    if fmt == 'i':  return str(int(v))
    if isinstance(v, float):
        return f"{v:.1f}"
    return str(v)

# ── Emit markdown ───────────────────────────────────────────
lines = []
lines.append("# Full Metrics Table")
lines.append("")
lines.append("All models.ini entries with benchmark data. RTX 3060 12GB.")
lines.append("")
lines.append("Generated by `tools/gen_metrics.sh` from `llama-cpp/models/*.json` + `models.ini`.")
lines.append("")
lines.append("## Columns")
lines.append("")
lines.append("| Column | Description |")
lines.append("|---|---|")
lines.append("| model | Section header name from models.ini |")
lines.append("| ctx | Context window size |")
lines.append("| batch | batch-size |")
lines.append("| n_max | spec-draft-n-max (MTP models only) |")
lines.append("| p_min | spec-draft-p-min (MTP models only) |")
lines.append("| drafter | in-model / Q4_0 root / none |")
lines.append("| reasoning | off / on / low / medium / high |")
lines.append("| decode_t/s | Decode speed (tokens per second) |")
lines.append("| prefill_t/s | Prefill speed (tokens per second) |")
lines.append("| prefill_ms | Total prefill latency (ms) |")
lines.append("| decode_ms | Total decode latency (ms) |")
lines.append("| pre_tok_ms | Per-token prefill time (ms) |")
lines.append("| dec_tok_ms | Per-token decode time (ms) |")
lines.append("| acc | Draft acceptance rate |")
lines.append("| placement | GPU / CPU / AMBIGUOUS / unverified |")
lines.append("| cpu% | Average CPU% during decode |")
lines.append("| gpu% | Average GPU utilization% |")
lines.append("| temp_c | GPU temperature (C) |")
lines.append("| power_w | GPU power draw (W) |")
lines.append("| vram | VRAM used (MiB) |")
lines.append("| ram | System RAM used (MiB) |")
lines.append("| rss | Process RSS (MiB) |")
lines.append("")
lines.append("## Notes")
lines.append("")
lines.append("- Rows with `unverified` placement have no bench JSON yet — run `./tools/bench_model.sh <model>` after batch bisect.")
lines.append("- Each model (including -coder variants) is benched independently — no values are copied between entries.")
lines.append("- decode_t/s measured over a full 4000-token window (150-token decode prompt); prefill over a 75%-ctx prompt.")
lines.append("")
lines.append("## Benchmark Data")
lines.append("")
lines.append("| model | ctx | batch | n_max | p_min | drafter | reasoning | decode_t/s | prefill_t/s | prefill_ms | decode_ms | pre_tok_ms | dec_tok_ms | acc | placement | cpu% | gpu% | temp_c | power_w | vram | ram | rss |")
lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")

for name, b in rows:
    lines.append("| " + " | ".join([
        f"`{name}`",
        fmt_ctx(b['ctx']),
        f(b['batch']),
        f(b['n_max']),
        f(b['p_min']),
        f(b['drafter']),
        f(b['reasoning']),
        f(b['decode'], 't1'),
        f(b['prefill'], 't1'),
        f(b['pre_ms'], 'i'),
        f(b['dec_ms'], 'i'),
        f(b['pre_mtok'], 't2'),
        f(b['dec_mtok'], 't2'),
        f(b['acc'], 't2'),
        f(b['place']),
        f(b['cpu'], 'i'),
        f(b['gpu_util'], 'i'),
        f(b['temp'], 'i'),
        f(b['power'], 'i'),
        f(b['vram'], 'i'),
        f(b['ram'], 'i'),
        f(b['rss'], 'i'),
    ]) + " |")

with open(out_path, 'w') as f:
    f.write("\n".join(lines) + "\n")

n_filled = sum(1 for _, b in rows if b['place'] not in ('unverified', None))
print(f"Generated {out_path} — {len(rows)} models, {n_filled} with bench data")
PYEOF
